services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fraudaware-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: fraudaware
      RABBITMQ_DEFAULT_PASS: fraudaware
    volumes:
      - rabbitmq_data:/data

volumes:
  rabbitmq_data:
