import type { SupportTicket } from './supportTypes';

/** Demo support tickets (no backend yet). */
export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt_001',
    subject: 'Cannot publish my job listing',
    description:
      'I finished the job form but Publish stays disabled. My company profile looks complete.',
    requesterName: 'Kajanthan Ulageeswaran',
    requesterEmail: 'kanthantharsil@gmail.com',
    requesterUserId: 'usr_co_01',
    status: 'open',
    priority: 'high',
    assigneeName: null,
    assigneeEmail: null,
    linkedType: 'job',
    linkedId: 'job_612',
    linkedLabel: 'Software Engineer — Optimize Solution',
    internalNote: null,
    messages: [
      {
        id: 'msg_001a',
        author: 'user',
        authorName: 'Kajanthan Ulageeswaran',
        body: 'Publish button is greyed out after I fill salary and description. Please help.',
        createdAt: '2026-08-23T07:20:00.000Z',
      },
    ],
    createdAt: '2026-08-23T07:20:00.000Z',
    updatedAt: '2026-08-23T07:20:00.000Z',
  },
  {
    id: 'tkt_002',
    subject: 'Verification still pending after 3 days',
    description:
      'We submitted company registration details last week. Still showing pending.',
    requesterName: 'Malini Gunasekara',
    requesterEmail: 'hiring@dialog.lk',
    requesterUserId: 'usr_co_dialog',
    status: 'in_progress',
    priority: 'medium',
    assigneeName: 'Alex Thompson',
    assigneeEmail: 'alex.thompson@fraudaware.lk',
    linkedType: 'user',
    linkedId: 'usr_co_dialog',
    linkedLabel: 'Dialog Axiata PLC',
    internalNote: 'Checking eROC match before approving.',
    messages: [
      {
        id: 'msg_002a',
        author: 'user',
        authorName: 'Malini Gunasekara',
        body: 'Registration number PQ 38. Can someone review today?',
        createdAt: '2026-08-21T10:00:00.000Z',
      },
      {
        id: 'msg_002b',
        author: 'admin',
        authorName: 'Alex Thompson',
        body: 'Thanks — we are reviewing your registry signals and will update soon.',
        createdAt: '2026-08-22T09:15:00.000Z',
      },
    ],
    createdAt: '2026-08-21T10:00:00.000Z',
    updatedAt: '2026-08-22T09:15:00.000Z',
  },
  {
    id: 'tkt_003',
    subject: 'Login OTP not arriving',
    description: 'Tried resend three times. No email in inbox or spam.',
    requesterName: 'Nimal Perera',
    requesterEmail: 'nimal.p@gmail.com',
    requesterUserId: 'usr_js_44',
    status: 'open',
    priority: 'high',
    assigneeName: null,
    linkedType: 'user',
    linkedId: 'usr_js_44',
    linkedLabel: 'Jobseeker · Nimal Perera',
    messages: [
      {
        id: 'msg_003a',
        author: 'user',
        authorName: 'Nimal Perera',
        body: 'I need to apply today. OTP never comes.',
        createdAt: '2026-08-23T08:05:00.000Z',
      },
    ],
    createdAt: '2026-08-23T08:05:00.000Z',
    updatedAt: '2026-08-23T08:05:00.000Z',
  },
  {
    id: 'tkt_004',
    subject: 'How do I report a scam recruiter in chat?',
    description: 'Looking for the report button inside InChat on mobile.',
    requesterName: 'Ayesha Mohamed',
    requesterEmail: 'ayesha.m@gmail.com',
    requesterUserId: 'usr_js_18',
    status: 'in_progress',
    priority: 'low',
    assigneeName: 'Maya Perera',
    assigneeEmail: 'maya.perera@fraudaware.lk',
    linkedType: 'report',
    linkedId: 'rpt_004',
    linkedLabel: 'Report · Recruiter HR Manager Priya',
    messages: [
      {
        id: 'msg_004a',
        author: 'user',
        authorName: 'Ayesha Mohamed',
        body: 'Where is Report in the chat menu?',
        createdAt: '2026-08-20T14:30:00.000Z',
      },
      {
        id: 'msg_004b',
        author: 'admin',
        authorName: 'Maya Perera',
        body: 'Open the thread → ⋮ menu → Report. We also opened a safety report for that recruiter.',
        createdAt: '2026-08-20T16:10:00.000Z',
      },
    ],
    createdAt: '2026-08-20T14:30:00.000Z',
    updatedAt: '2026-08-20T16:10:00.000Z',
  },
  {
    id: 'tkt_005',
    subject: 'Refund request for premium boost',
    description: 'Boosted a job that was later force-closed. Requesting refund.',
    requesterName: 'TechVista Hiring',
    requesterEmail: 'jobs@techvista.lk',
    requesterUserId: 'usr_co_tv',
    status: 'closed',
    priority: 'medium',
    assigneeName: 'Alex Thompson',
    assigneeEmail: 'alex.thompson@fraudaware.lk',
    linkedType: 'job',
    linkedId: 'job_812',
    linkedLabel: 'Marketing Intern — unpaid trial week',
    internalNote: 'Refund processed manually; closed.',
    messages: [
      {
        id: 'msg_005a',
        author: 'user',
        authorName: 'TechVista Hiring',
        body: 'Our boosted job was removed. Can we get the boost fee back?',
        createdAt: '2026-08-18T11:00:00.000Z',
      },
      {
        id: 'msg_005b',
        author: 'admin',
        authorName: 'Alex Thompson',
        body: 'Refund approved. You should see it in 3–5 business days.',
        createdAt: '2026-08-19T09:40:00.000Z',
      },
    ],
    createdAt: '2026-08-18T11:00:00.000Z',
    updatedAt: '2026-08-19T09:40:00.000Z',
  },
  {
    id: 'tkt_006',
    subject: 'Wrong account type selected at signup',
    description: 'Registered as company by mistake; need recruiter account.',
    requesterName: 'Sajani Fernando',
    requesterEmail: 'sajani.f@outlook.com',
    requesterUserId: 'usr_rec_09',
    status: 'open',
    priority: 'low',
    assigneeName: null,
    linkedType: 'none',
    messages: [
      {
        id: 'msg_006a',
        author: 'user',
        authorName: 'Sajani Fernando',
        body: 'Can you switch my account type without losing email verification?',
        createdAt: '2026-08-22T17:45:00.000Z',
      },
    ],
    createdAt: '2026-08-22T17:45:00.000Z',
    updatedAt: '2026-08-22T17:45:00.000Z',
  },
];
