import type { ModeratedJob } from './jobModerationTypes';

/** Demo flagged / fake job listings for Super Admin moderation. */
export const MOCK_MODERATED_JOBS: ModeratedJob[] = [
  {
    id: 'job_mod_001',
    title: 'Work From Home Data Entry — Earn $500/day',
    companyName: 'QuickCash Global',
    posterType: 'recruiter',
    posterName: 'Omar Hassan',
    posterEmail: 'omar@quickhire.agency',
    location: 'Remote',
    mode: 'Remote',
    type: 'Part-Time',
    salaryLabel: 'USD 500 / day',
    description:
      'No experience needed. Just send a registration fee of $49 via crypto wallet to unlock onboarding documents. Daily payouts guaranteed.',
    listingStatus: 'active',
    moderationStatus: 'flagged',
    fakeJobScore: 0.94,
    flagReasons: ['fake_job_model', 'payment_request', 'user_report'],
    reportCount: 11,
    applicants: 48,
    postedAt: '2026-07-18T08:10:00.000Z',
    flaggedAt: '2026-07-18T09:05:00.000Z',
  },
  {
    id: 'job_mod_002',
    title: 'Senior React Engineer',
    companyName: 'WSO2',
    posterType: 'company',
    posterName: 'Tharindu Pathirana',
    posterEmail: 'careers@wso2.com',
    location: 'Colombo',
    mode: 'Hybrid',
    type: 'Full-Time',
    salaryLabel: 'LKR 350,000 – 450,000',
    description:
      'Build developer tooling and cloud products. 5+ years React/TypeScript. Competitive benefits and hybrid office in Colombo.',
    listingStatus: 'active',
    moderationStatus: 'flagged',
    fakeJobScore: 0.22,
    flagReasons: ['user_report'],
    reportCount: 1,
    applicants: 17,
    postedAt: '2026-07-15T11:30:00.000Z',
    flaggedAt: '2026-07-20T14:12:00.000Z',
  },
  {
    id: 'job_mod_003',
    title: 'Overseas Nursing Placement — Free Visa',
    companyName: 'Island Hire Solutions',
    posterType: 'recruiter',
    posterName: 'Sahan Dias',
    posterEmail: 'ops@islandhire.example',
    location: 'Dubai',
    mode: 'On-Site',
    type: 'Contract',
    salaryLabel: 'AED 8,000+',
    description:
      'Immediate openings for nurses. Processing fee required before interview. WhatsApp only communication. Limited slots this week.',
    listingStatus: 'active',
    moderationStatus: 'flagged',
    fakeJobScore: 0.88,
    flagReasons: ['fake_job_model', 'payment_request', 'duplicate_scam_pattern'],
    reportCount: 7,
    applicants: 32,
    postedAt: '2026-07-19T16:40:00.000Z',
    flaggedAt: '2026-07-19T17:10:00.000Z',
  },
  {
    id: 'job_mod_004',
    title: 'Marketing Intern',
    companyName: 'TechVista Pvt Ltd',
    posterType: 'company',
    posterName: 'Emily Chen',
    posterEmail: 'jobs@techvista.lk',
    location: 'Kandy',
    mode: 'On-Site',
    type: 'Internship',
    salaryLabel: 'LKR 25,000 stipend',
    description:
      'Support social media campaigns and content calendars. 3-month internship with possible conversion.',
    listingStatus: 'active',
    moderationStatus: 'cleared',
    fakeJobScore: 0.18,
    flagReasons: ['user_report'],
    reportCount: 1,
    applicants: 9,
    postedAt: '2026-07-10T09:00:00.000Z',
    flaggedAt: '2026-07-11T10:20:00.000Z',
    reviewedAt: '2026-07-12T08:45:00.000Z',
  },
  {
    id: 'job_mod_005',
    title: 'Telegram Crypto Trading Coach',
    companyName: 'FakeCorp Global',
    posterType: 'company',
    posterName: 'Rajiv Menon',
    posterEmail: 'hr@fakecorp-scam.com',
    location: 'Remote',
    mode: 'Remote',
    type: 'Contract',
    salaryLabel: 'Commission only',
    description:
      'Join our VIP signal group. Deposit training capital first. Guaranteed returns within 7 days.',
    listingStatus: 'closed',
    moderationStatus: 'force_closed',
    fakeJobScore: 0.97,
    flagReasons: [
      'fake_job_model',
      'payment_request',
      'suspicious_employer',
      'user_report',
    ],
    reportCount: 19,
    applicants: 61,
    postedAt: '2026-07-08T07:25:00.000Z',
    flaggedAt: '2026-07-08T07:50:00.000Z',
    reviewedAt: '2026-07-08T12:00:00.000Z',
    closeReason: 'Clear scam pattern: upfront payment + unrealistic returns.',
  },
  {
    id: 'job_mod_006',
    title: 'Customer Support Associate',
    companyName: 'Dialog Axiata',
    posterType: 'company',
    posterName: 'Malini Gunasekara',
    posterEmail: 'hiring@dialog.lk',
    location: 'Colombo',
    mode: 'On-Site',
    type: 'Full-Time',
    salaryLabel: 'LKR 90,000 – 120,000',
    description:
      'Handle inbound customer queries across voice and chat channels. Prior contact-center experience preferred.',
    listingStatus: 'active',
    moderationStatus: 'flagged',
    fakeJobScore: 0.31,
    flagReasons: ['suspicious_employer'],
    reportCount: 2,
    applicants: 24,
    postedAt: '2026-07-17T13:15:00.000Z',
    flaggedAt: '2026-07-21T06:40:00.000Z',
  },
  {
    id: 'job_mod_007',
    title: 'Warehouse Helper — Same Day Cash',
    companyName: 'Lanka Talent',
    posterType: 'recruiter',
    posterName: 'Priya Wijesinghe',
    posterEmail: 'priya@lankatalent.com',
    location: 'Negombo',
    mode: 'On-Site',
    type: 'Part-Time',
    salaryLabel: 'LKR 3,500 / day cash',
    description:
      'Need 20 helpers tomorrow. Pay cash after shift. Bring NIC copy via WhatsApp before arriving.',
    listingStatus: 'active',
    moderationStatus: 'flagged',
    fakeJobScore: 0.72,
    flagReasons: ['fake_job_model', 'duplicate_scam_pattern', 'user_report'],
    reportCount: 5,
    applicants: 40,
    postedAt: '2026-07-20T18:05:00.000Z',
    flaggedAt: '2026-07-20T18:40:00.000Z',
  },
];
