import type { AuditLogEntry } from './auditTypes';

/** Demo admin audit trail (no backend yet). */
export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'aud_001',
    createdAt: '2026-08-23T12:10:00.000Z',
    actorId: 'admin_001',
    actorName: 'Alex Thompson',
    actorEmail: 'alex.thompson@fraudaware.lk',
    action: 'job.force_close',
    targetType: 'job',
    targetId: 'job_901',
    targetLabel: 'Work from home — earn LKR 80,000/week',
    summary: 'Force-closed flagged listing after payment-request report',
    before: { moderationStatus: 'flagged', listingStatus: 'pending_review' },
    after: { moderationStatus: 'force_closed', listingStatus: 'closed' },
    note: 'Poster asked for registration fee on WhatsApp.',
  },
  {
    id: 'aud_002',
    createdAt: '2026-08-23T11:42:00.000Z',
    actorId: 'admin_001',
    actorName: 'Alex Thompson',
    actorEmail: 'alex.thompson@fraudaware.lk',
    action: 'user.suspend',
    targetType: 'user',
    targetId: 'usr_220',
    targetLabel: 'Recruiter · HR Manager Priya',
    summary: 'Suspended recruiter account for harassment reports',
    before: { accountStatus: 'active' },
    after: { accountStatus: 'suspended' },
    note: 'Multiple InChat harassment reports in 48h.',
  },
  {
    id: 'aud_003',
    createdAt: '2026-08-22T16:05:00.000Z',
    actorId: 'admin_002',
    actorName: 'Maya Perera',
    actorEmail: 'maya.perera@fraudaware.lk',
    action: 'company.verify.approve',
    targetType: 'company',
    targetId: 'co_dialog',
    targetLabel: 'Dialog Axiata PLC',
    summary: 'Approved company legitimacy verification',
    before: { decision: 'pending', isVerified: false },
    after: { decision: 'approved', isVerified: true },
    note: 'eROC + CSE signals matched.',
  },
  {
    id: 'aud_004',
    createdAt: '2026-08-22T15:20:00.000Z',
    actorId: 'admin_002',
    actorName: 'Maya Perera',
    actorEmail: 'maya.perera@fraudaware.lk',
    action: 'company.verify.reject',
    targetType: 'company',
    targetId: 'co_441',
    targetLabel: 'GlobalHire Express Pvt Ltd',
    summary: 'Rejected company verification',
    before: { decision: 'pending', isVerified: false },
    after: { decision: 'rejected', isVerified: false },
    note: 'Registration number not found; impersonation risk.',
  },
  {
    id: 'aud_005',
    createdAt: '2026-08-21T10:15:00.000Z',
    actorId: 'admin_001',
    actorName: 'Alex Thompson',
    actorEmail: 'alex.thompson@fraudaware.lk',
    action: 'job.clear',
    targetType: 'job',
    targetId: 'job_612',
    targetLabel: 'Software Engineer — Optimize Solution',
    summary: 'Cleared flagged job and published to jobseekers',
    before: { moderationStatus: 'flagged', listingStatus: 'pending_review' },
    after: { moderationStatus: 'cleared', listingStatus: 'active' },
    note: 'False positive from fake-job model; description looks legitimate.',
  },
  {
    id: 'aud_006',
    createdAt: '2026-08-20T14:00:00.000Z',
    actorId: 'admin_002',
    actorName: 'Maya Perera',
    actorEmail: 'maya.perera@fraudaware.lk',
    action: 'report.resolve',
    targetType: 'report',
    targetId: 'rpt_006',
    targetLabel: 'Report · Marketing Intern — unpaid trial week',
    summary: 'Resolved user report after force-closing listing',
    before: { status: 'reviewing' },
    after: { status: 'resolved' },
    note: 'Force-closed listing and warned company account.',
  },
  {
    id: 'aud_007',
    createdAt: '2026-08-19T09:30:00.000Z',
    actorId: 'admin_001',
    actorName: 'Alex Thompson',
    actorEmail: 'alex.thompson@fraudaware.lk',
    action: 'user.ban',
    targetType: 'user',
    targetId: 'usr_991',
    targetLabel: 'Company · QuickCash Solutions',
    summary: 'Banned repeat scam company account',
    before: { accountStatus: 'suspended' },
    after: { accountStatus: 'banned' },
    note: 'Repeat payment-request pattern across 3 listings.',
  },
  {
    id: 'aud_008',
    createdAt: '2026-08-18T18:05:00.000Z',
    actorId: 'admin_002',
    actorName: 'Maya Perera',
    actorEmail: 'maya.perera@fraudaware.lk',
    action: 'report.dismiss',
    targetType: 'report',
    targetId: 'rpt_007',
    targetLabel: 'Report · QuickCash Solutions',
    summary: 'Dismissed duplicate report',
    before: { status: 'new' },
    after: { status: 'dismissed' },
    note: 'Duplicate of earlier case; company already banned.',
  },
  {
    id: 'aud_009',
    createdAt: '2026-08-17T11:00:00.000Z',
    actorId: 'admin_001',
    actorName: 'Alex Thompson',
    actorEmail: 'alex.thompson@fraudaware.lk',
    action: 'user.restore',
    targetType: 'user',
    targetId: 'usr_118',
    targetLabel: 'Recruiter · TechVista Hiring',
    summary: 'Restored suspended recruiter after appeal',
    before: { accountStatus: 'suspended' },
    after: { accountStatus: 'active' },
    note: 'Appeal accepted; prior flag was mistaken identity.',
  },
];
