import type { PlatformReport } from './reportTypes';

/** Demo user-submitted reports queue (no backend yet). */
export const MOCK_REPORTS_QUEUE: PlatformReport[] = [
  {
    id: 'rpt_001',
    targetType: 'job',
    targetId: 'job_901',
    targetLabel: 'Work from home — earn LKR 80,000/week',
    reporterName: 'Nimal Perera',
    reporterEmail: 'nimal.p@gmail.com',
    reasonCode: 'payment_request',
    details:
      'The poster asked me to pay a “registration fee” on WhatsApp before sharing the interview link.',
    status: 'new',
    createdAt: '2026-08-23T08:15:00.000Z',
  },
  {
    id: 'rpt_002',
    targetType: 'company',
    targetId: 'co_441',
    targetLabel: 'GlobalHire Express Pvt Ltd',
    reporterName: 'Sajani Fernando',
    reporterEmail: 'sajani.f@outlook.com',
    reasonCode: 'impersonation',
    details:
      'Company claims to be Dialog hiring partners. Website looks cloned and registration number looks fake.',
    status: 'new',
    createdAt: '2026-08-22T19:40:00.000Z',
  },
  {
    id: 'rpt_003',
    targetType: 'job',
    targetId: 'job_877',
    targetLabel: 'Data Entry Assistant — Immediate start',
    reporterName: 'Kasun Jayasinghe',
    reporterEmail: 'kasun.j@yahoo.com',
    reasonCode: 'fake_job',
    details:
      'Same description posted under three different company names this week. Asking for NIC copy by email.',
    status: 'reviewing',
    createdAt: '2026-08-22T11:05:00.000Z',
  },
  {
    id: 'rpt_004',
    targetType: 'user',
    targetId: 'usr_220',
    targetLabel: 'Recruiter · “HR Manager Priya”',
    reporterName: 'Ayesha Mohamed',
    reporterEmail: 'ayesha.m@gmail.com',
    reasonCode: 'harassment',
    details:
      'Sent inappropriate personal messages after I applied. Refused to stay on InChat.',
    status: 'reviewing',
    createdAt: '2026-08-21T16:20:00.000Z',
  },
  {
    id: 'rpt_005',
    targetType: 'message',
    targetId: 'msg_thread_55',
    targetLabel: 'InChat thread · Software Engineer role',
    reporterName: 'Tharindu Silva',
    reporterEmail: 'tharindu.s@gmail.com',
    reasonCode: 'spam',
    details:
      'Recruiter keeps sending crypto “side hustle” links unrelated to the job.',
    status: 'new',
    createdAt: '2026-08-23T06:50:00.000Z',
  },
  {
    id: 'rpt_006',
    targetType: 'job',
    targetId: 'job_812',
    targetLabel: 'Marketing Intern — unpaid trial week',
    reporterName: 'Ishara Bandara',
    reporterEmail: 'ishara.b@gmail.com',
    reasonCode: 'other',
    details:
      'Job post says unpaid “training fee” after joining. Want admin to check before I apply.',
    status: 'resolved',
    createdAt: '2026-08-19T09:10:00.000Z',
    resolvedAt: '2026-08-20T14:00:00.000Z',
    adminNote: 'Force-closed listing and warned company account.',
  },
  {
    id: 'rpt_007',
    targetType: 'company',
    targetId: 'co_118',
    targetLabel: 'QuickCash Solutions',
    reporterName: 'Ruvini De Silva',
    reporterEmail: 'ruvini.d@gmail.com',
    reasonCode: 'fake_job',
    details: 'Multiple friends reported the same scam. Please dismiss if duplicate.',
    status: 'dismissed',
    createdAt: '2026-08-18T13:30:00.000Z',
    resolvedAt: '2026-08-18T18:05:00.000Z',
    adminNote: 'Duplicate of earlier case; company already banned.',
  },
];
