import type { CompanyVerificationRequest } from './verificationTypes';

/** Demo company legitimacy queue for Super Admin (no backend yet). */
export const MOCK_VERIFICATION_QUEUE: CompanyVerificationRequest[] = [
  {
    id: 'ver_001',
    companyName: 'Dialog Axiata PLC',
    registrationNumber: 'PQ 38',
    website: 'https://www.dialog.lk',
    industry: 'Telecommunications',
    address: 'No. 475, Union Place, Colombo 02',
    submittedByName: 'Malini Gunasekara',
    submittedByEmail: 'hiring@dialog.lk',
    submittedAt: '2026-07-18T09:20:00.000Z',
    riskScore: 0.12,
    summary:
      'Strong registry match. Listed on CSE and found in eROC under matching legal name.',
    registrySignals: [
      { source: 'eROC', found: true, note: 'Active company record matched' },
      { source: 'CSE', found: true, note: 'Listed equity issuer' },
      { source: 'OpenCorporates', found: true, note: 'Jurisdiction LK match' },
    ],
    decision: 'pending',
  },
  {
    id: 'ver_002',
    companyName: 'TechVista Pvt Ltd',
    registrationNumber: 'PV 00234567',
    website: 'https://techvista.lk',
    industry: 'Software',
    address: 'Kandy City Centre, Kandy',
    submittedByName: 'Emily Chen',
    submittedByEmail: 'jobs@techvista.lk',
    submittedAt: '2026-07-19T14:05:00.000Z',
    riskScore: 0.41,
    summary:
      'eROC match found, but website domain age is recent and no CSE listing. Manual review recommended.',
    registrySignals: [
      { source: 'eROC', found: true, note: 'Private limited company found' },
      { source: 'CSE', found: false, note: 'Not a listed company' },
      { source: 'OpenCorporates', found: false, note: 'No confident match' },
    ],
    decision: 'pending',
  },
  {
    id: 'ver_003',
    companyName: 'FakeCorp Global',
    registrationNumber: 'PV 99999999',
    website: 'https://fakecorp-scam.com',
    industry: 'Recruitment',
    address: 'Unknown / Virtual mailbox',
    submittedByName: 'Rajiv Menon',
    submittedByEmail: 'hr@fakecorp-scam.com',
    submittedAt: '2026-07-20T07:40:00.000Z',
    riskScore: 0.91,
    summary:
      'No registry matches. Domain flagged in scam heuristics. High likelihood of fraudulent employer.',
    registrySignals: [
      { source: 'eROC', found: false, note: 'Registration number not found' },
      { source: 'CSE', found: false, note: 'Not listed' },
      { source: 'OpenCorporates', found: false, note: 'No match' },
      { source: 'Heuristics', found: true, note: 'Suspicious domain + mailbox pattern' },
    ],
    decision: 'pending',
  },
  {
    id: 'ver_004',
    companyName: 'WSO2 Lanka (Private) Limited',
    registrationNumber: 'PV 4835',
    website: 'https://wso2.com',
    industry: 'Enterprise Software',
    address: 'Colombo',
    submittedByName: 'Tharindu Pathirana',
    submittedByEmail: 'careers@wso2.com',
    submittedAt: '2026-07-12T11:15:00.000Z',
    riskScore: 0.18,
    summary: 'Consistent branding and registry signals. Previously approved by admin.',
    registrySignals: [
      { source: 'eROC', found: true, note: 'Active private company' },
      { source: 'CSE', found: false, note: 'Not listed' },
      { source: 'OpenCorporates', found: true, note: 'Name match' },
    ],
    decision: 'approved',
    reviewedAt: '2026-07-13T08:00:00.000Z',
  },
  {
    id: 'ver_005',
    companyName: 'Island Hire Solutions',
    registrationNumber: 'PV 00112233',
    website: 'https://islandhire.example',
    industry: 'Staffing',
    address: 'Nugegoda',
    submittedByName: 'Sahan Dias',
    submittedByEmail: 'ops@islandhire.example',
    submittedAt: '2026-07-10T16:30:00.000Z',
    riskScore: 0.67,
    summary:
      'Partial name collision with an existing registered firm. Website does not resolve to claimed address.',
    registrySignals: [
      { source: 'eROC', found: false, note: 'Number mismatch' },
      { source: 'CSE', found: false, note: 'Not listed' },
      { source: 'Heuristics', found: true, note: 'Address inconsistency' },
    ],
    decision: 'rejected',
    reviewedAt: '2026-07-11T10:20:00.000Z',
    rejectionReason: 'Registration details could not be verified against eROC.',
  },
  {
    id: 'ver_006',
    companyName: 'MAS Holdings (Private) Limited',
    registrationNumber: 'PV 3321',
    website: 'https://www.masholdings.com',
    industry: 'Apparel',
    address: 'Colombo',
    submittedByName: 'Ishara Peris',
    submittedByEmail: 'recruitment@mas.lk',
    submittedAt: '2026-07-21T06:50:00.000Z',
    riskScore: 0.15,
    summary: 'Clear eROC match and established corporate footprint. Pending final admin sign-off.',
    registrySignals: [
      { source: 'eROC', found: true, note: 'Active company record' },
      { source: 'CSE', found: false, note: 'Not listed' },
      { source: 'OpenCorporates', found: true, note: 'Strong name match' },
    ],
    decision: 'pending',
  },
];
